-- حساب‌های کاربری سایت. این migration فقط افزایشی است و اجرای دوباره‌اش بی‌خطر است.
BEGIN;

CREATE TABLE IF NOT EXISTS user_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL CHECK (length(btrim(email)) BETWEEN 5 AND 320),
  display_name TEXT NOT NULL CHECK (length(btrim(display_name)) BETWEEN 2 AND 80),
  profile_slug TEXT NOT NULL UNIQUE CHECK (profile_slug ~ '^u-[a-z0-9-]+$'),
  password_hash TEXT NOT NULL CHECK (password_hash LIKE 'scrypt$%'),
  bio TEXT NOT NULL DEFAULT '' CHECK (length(bio) <= 280),
  avatar_color TEXT NOT NULL DEFAULT '#2563eb' CHECK (avatar_color ~ '^#[0-9A-Fa-f]{6}$'),
  notify_likes BOOLEAN NOT NULL DEFAULT TRUE,
  notify_publication BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS user_accounts_email_ci_unique ON user_accounts (lower(email));

CREATE TABLE IF NOT EXISTS user_sessions (
  token_hash CHAR(64) PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS user_sessions_user_id_idx ON user_sessions (user_id);

-- مالکیت برای محتوایی که از حساب کاربری منتشر می‌شود.
ALTER TABLE images ADD COLUMN IF NOT EXISTS author_user_id BIGINT REFERENCES user_accounts(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS images_author_user_id_idx ON images (author_user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS user_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL CHECK (length(btrim(image_url)) > 0),
  prompt_text TEXT NOT NULL CHECK (length(btrim(prompt_text)) <= 20000),
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  model_used TEXT CHECK (model_used IS NULL OR length(model_used) <= 120),
  status TEXT NOT NULL DEFAULT 'pending_review' CHECK (status IN ('pending_review', 'approved', 'rejected')),
  published_image_id BIGINT UNIQUE REFERENCES images(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  reviewed_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS user_submissions_user_status_idx ON user_submissions (user_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS user_submissions_review_idx ON user_submissions (status, created_at DESC);

COMMIT;
