-- کتابخانهٔ شخصی کاربر: ذخیره‌ها و تاریخچهٔ کپیِ پرامپت.
BEGIN;

CREATE TABLE IF NOT EXISTS user_saved_images (
  user_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
  image_id BIGINT NOT NULL REFERENCES images(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, image_id)
);
CREATE INDEX IF NOT EXISTS user_saved_images_user_created_idx ON user_saved_images (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS user_copy_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
  image_id BIGINT NOT NULL REFERENCES images(id) ON DELETE CASCADE,
  copied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS user_copy_history_user_copied_idx ON user_copy_history (user_id, copied_at DESC);

COMMIT;
