import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { connection } from "next/server";
import { notFound } from "next/navigation";
import { Avatar } from "@/app/_components/account/AccountShell";
import { SiteChrome } from "@/app/_components/website/SiteChrome";
import { getPublicProfile, listPublishedImages } from "@/lib/users/queries";
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { await connection(); const profile = await getPublicProfile((await params).slug); return profile ? { title: profile.display_name } : { title: "پروفایل پیدا نشد" }; }
export default async function PublicProfilePage({ params }: { params: Promise<{ slug: string }> }) { await connection(); const profile = await getPublicProfile((await params).slug); if (!profile) notFound(); const images = await listPublishedImages(profile.id); return <SiteChrome><main dir="rtl" className="mx-auto w-full max-w-4xl px-5 py-10 md:px-8"><section className="rounded-card border border-line bg-white p-6"><div className="flex items-start gap-4"><Avatar name={profile.display_name} color={profile.avatar_color} size="size-[72px]" /><div><h1 className="text-2xl font-extrabold text-ink">{profile.display_name}</h1>{profile.bio && <p className="mt-2 max-w-xl text-sm leading-7 text-muted">{profile.bio}</p>}<p className="mt-3 text-xs text-faint">عضو از {new Intl.DateTimeFormat("fa-IR", { year: "numeric", month: "long" }).format(profile.created_at)}</p></div></div><p className="mt-6 border-t border-line pt-5 text-sm text-muted"><strong className="text-xl text-accent">{images.length.toLocaleString("fa-IR")}</strong> پرامپت منتشرشده</p></section><h2 className="mt-8 text-lg font-extrabold text-ink">پرامپت‌های منتشرشده</h2>{images.length === 0 ? <p className="mt-4 rounded-card border border-dashed border-line bg-surface p-8 text-center text-sm text-muted">هنوز پرامپتی منتشر نشده.</p> : <div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-3">{images.map((image) => <Link key={image.id} href={`/image/${image.id}`} className="group overflow-hidden rounded-card border border-line bg-white"><Image src={image.url} alt={image.title_fa ?? "پرامپت منتشرشده"} width={600} height={450} className="aspect-[4/3] w-full object-cover transition-transform group-hover:scale-[1.03]" /><p className="truncate px-3 py-2 text-xs font-bold text-ink">{image.title_fa ?? "پرامپت"}</p></Link>)}</div>}</main></SiteChrome>; }
