-- ===========================================================================
--  گالری پرامپت — اسکیمای دیتابیس (Postgres / Liara)
--  مبنا: بخش ۷ سند PRD
-- ===========================================================================
--
--  اجرا:
--    psql "$DATABASE_URL" -f db/schema.sql
--  یا در پنل Liara → دیتابیس → کنسول SQL، محتوای این فایل را paste کن.
--
--  این فایل idempotent است: چند بار اجرا کردنش خطا نمی‌دهد و داده‌ای را
--  پاک نمی‌کند. کل فایل داخل یک تراکنش است، پس اگر وسط کار خطایی رخ دهد
--  هیچ تغییری نیمه‌کاره باقی نمی‌ماند.
--
--  نکته درباره id ها: از GENERATED BY DEFAULT AS IDENTITY استفاده شده تا اگر
--  بعداً محتوا را از CSV با idهای مشخص import کردی امکانش باشد. در آن حالت
--  یادت باشد sequence را جلو بکشی، وگرنه insertهای بعدی به تضاد id می‌خورند:
--    SELECT setval(pg_get_serial_sequence('images','id'), (SELECT MAX(id) FROM images));
-- ===========================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- دسته‌بندی‌ها — تب‌های بالای گالری (کاپل، پروفایل، هنری، فانتزی، طبیعت)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- نام فارسی که در رابط کاربری نمایش داده می‌شود
    name_fa TEXT NOT NULL CHECK (length(btrim(name_fa)) > 0),
    -- شناسه لاتین برای URL (مثلاً /category/couple) — باید یکتا و URL-safe باشد
    slug    TEXT NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    -- توضیح کوتاه، برای پنل مدیریت (migration 002). nullable چون دسته‌های
    -- موجود توضیحی ندارند و گالری عمومی هم از آن استفاده نمی‌کند.
    description TEXT
);

COMMENT ON TABLE categories IS 'دسته‌بندی تصاویر؛ منبع تب‌های فیلتر گالری';
COMMENT ON COLUMN categories.slug IS 'شناسه لاتین URL-safe، برای مسیر صفحه دسته و سئو';
COMMENT ON COLUMN categories.description IS 'توضیح کوتاه دسته؛ فقط در پنل مدیریت و در صورت نیاز برای سئوی صفحه دسته';

-- ---------------------------------------------------------------------------
-- تصاویر — رکورد اصلی گالری
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS images (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- آدرس فایل تصویر (فعلاً فایل محلی در public/، بعداً استوریج/CDN)
    url         TEXT NOT NULL CHECK (length(btrim(url)) > 0),
    -- عنوان فارسی: برای متن alt، سئوی فارسی و شناسایی رکورد در پنل ادمین.
    -- در اسکیمای بخش ۷ نبود و با تایید صریح اضافه شده است.
    title_fa    TEXT,
    -- توجه: دسته‌بندی روی خود images نیست. چون یک عکس می‌تواند چند دسته داشته
    -- باشد، رابطه در جدول واسط image_categories نگه‌داری می‌شود (پایین‌تر).
    -- مدل AI سازنده تصویر (Midjourney، DALL·E، ...) — در مودال جزئیات نمایش داده می‌شود
    model_used  TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- ابعاد ذاتی تصویر به پیکسل. کامپوننت <Image> نکست برای جلوگیری از پرش
    -- چیدمان (CLS) و ساخت srcset درست به width/height نیاز دارد.
    --
    -- چرا در دیتابیس و نه خواندن از فایل؟ خواندن از فایل‌سیستم یعنی به ازای هر
    -- رندر صفحه، به تعداد عکس‌ها فایل باز شود (برای ۷۰۰ عکس ~۱۱۶ مگابایت)، و
    -- وقتی تصاویر به object storage بروند اصلاً فایل محلی وجود ندارد. پس ابعاد
    -- یک‌بار در زمان import/آپلود خوانده و همین‌جا ذخیره می‌شود.
    --
    -- nullable است چون یک عکس بدون ابعادِ خوانده‌شده هم باید قابل ثبت باشد؛
    -- صفحه در آن حالت به نسبت‌تصویر پیش‌فرض برمی‌گردد. CHECK جلوی مقدار صفر و
    -- منفی را می‌گیرد تا مقدار بی‌معنا وارد optimizer نشود.
    width       INTEGER CHECK (width  IS NULL OR width  > 0),
    height      INTEGER CHECK (height IS NULL OR height > 0),
    -- شمارنده لایک برای مرتب‌سازی «محبوب‌ترین». طبق تصمیم فعلی جدول likes
    -- جداگانه نداریم، پس این شمارنده تنها منبع است.
    likes_count INTEGER NOT NULL DEFAULT 0 CHECK (likes_count >= 0),
    -- آخرین ویرایش از طریق پنل مدیریت (migration 002). عمداً trigger ندارد و
    -- پنل خودش در همان UPDATE مقدارش را می‌گذارد، وگرنه هر اجرای دوباره‌ی
    -- اسکریپت import همه‌ی ردیف‌ها را «ویرایش‌شده‌ی امروز» نشان می‌داد.
    -- NULL یعنی از ابتدا دست‌نخورده.
    updated_at  TIMESTAMPTZ
);

COMMENT ON TABLE images IS 'تصاویر گالری؛ دسته‌ها از طریق جدول واسط image_categories وصل می‌شوند';
COMMENT ON COLUMN images.likes_count IS 'شمارنده لایک بدون ثبت‌نام؛ فعلاً بدون جدول likes و بدون جلوگیری از تکرار';
COMMENT ON COLUMN images.width IS 'عرض ذاتی تصویر به پیکسل؛ در زمان import از هدر فایل خوانده می‌شود';
COMMENT ON COLUMN images.height IS 'ارتفاع ذاتی تصویر به پیکسل؛ در زمان import از هدر فایل خوانده می‌شود';
COMMENT ON COLUMN images.updated_at IS 'آخرین ویرایش از طریق پنل مدیریت؛ NULL یعنی از ابتدا دست‌نخورده. بدون trigger، عمداً';

-- ---------------------------------------------------------------------------
-- پرامپت‌ها — متن قابل کپی هر تصویر
-- ---------------------------------------------------------------------------
-- رابطه یک‌به‌یک است: UNIQUE روی image_id تضمین می‌کند هر تصویر حداکثر یک
-- پرامپت داشته باشد. این تصمیم آگاهانه برای سادگی MVP گرفته شده — کوئری
-- مودال جزئیات لازم نیست بین چند پرامپت انتخاب کند و داده متناقض غیرممکن
-- می‌شود. اگر بعداً واریانت پرامپت (نسخه فارسی/انگلیسی یا مدل‌های مختلف)
-- لازم شد، برداشتن این UNIQUE یک migration کوچک است:
--   ALTER TABLE prompts DROP CONSTRAINT prompts_image_id_key;
CREATE TABLE IF NOT EXISTS prompts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- ON DELETE CASCADE: پرامپت بدون تصویرش بی‌معناست
    -- UNIQUE: یک پرامپت به ازای هر تصویر (و ایندکس جست‌وجو را هم خودش می‌سازد)
    image_id    BIGINT NOT NULL UNIQUE REFERENCES images (id) ON DELETE CASCADE,
    -- متن پرامپت؛ در UI به‌صورت LTR و مونواسپیس نمایش داده می‌شود (بخش ۸)
    prompt_text TEXT NOT NULL CHECK (length(btrim(prompt_text)) > 0),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE prompts IS 'متن پرامپت هر تصویر؛ رابطه یک‌به‌یک با images';

-- ---------------------------------------------------------------------------
-- رابطه عکس ↔ دسته (چند‌به‌چند)
-- ---------------------------------------------------------------------------
-- یک عکس می‌تواند در چند دسته باشد و هر دسته چند عکس دارد، پس رابطه در یک
-- جدول واسط نگه‌داری می‌شود نه به‌صورت ستون روی images.
--  • کلید اصلی مرکب (image_id, category_id) جفت تکراری را غیرممکن می‌کند و
--    خودش یک ایندکس روی (image_id, ...) می‌سازد که برای «دسته‌های این عکس» کافی است.
--  • هر دو FK با ON DELETE CASCADE: پاک‌شدن عکس یا دسته فقط ردیف‌های واسط را
--    برمی‌دارد. حذف یک دسته، عکس‌ها را نگه می‌دارد و صرفاً برچسبش را می‌کند
--    (شاید عکسی بی‌دسته شود). اجبارِ «حداقل یک دسته» عمداً در دیتابیس نیست و
--    به کنترل سمت پنل ادمین سپرده شده است.
CREATE TABLE IF NOT EXISTS image_categories (
    image_id    BIGINT NOT NULL REFERENCES images (id)     ON DELETE CASCADE,
    category_id BIGINT NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
    PRIMARY KEY (image_id, category_id)
);

COMMENT ON TABLE image_categories IS 'رابطه چند‌به‌چند عکس و دسته؛ هر ردیف یک عضویت است';

-- ---------------------------------------------------------------------------
-- صف بازبینی محتوای اتومات (اتوماسیون n8n)
-- ---------------------------------------------------------------------------
-- n8n محتوا را از کانال منبع برمی‌دارد و اینجا می‌ریزد. هیچ رکوردی مستقیم
-- وارد images/prompts نمی‌شود؛ اول باید دستی تایید شود. دلیلش بخش ۱۱ و درس
-- گرفته‌شده از رقیب در بخش ۱۴ است: کنترل کیفیت پرامپت قبل از انتشار.
CREATE TABLE IF NOT EXISTS pending_prompts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url         TEXT NOT NULL CHECK (length(btrim(image_url)) > 0),
    -- کپشن خام و دست‌نخورده‌ی پست منبع (برای بازبینی انسانی)
    raw_caption       TEXT,
    -- پرامپت استخراج‌شده از کپشن؛ ممکن است n8n نتواند استخراج کند، پس nullable
    prompt_text       TEXT,
    source_channel    TEXT,
    source_message_id TEXT,
    -- زمان انتشار در منبع (با زمان ورود به دیتابیس تفاوت دارد)
    posted_at         TIMESTAMPTZ,
    status            TEXT NOT NULL DEFAULT 'pending_review'
                      CHECK (status IN ('pending_review', 'approved', 'rejected')),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE pending_prompts IS 'صف بازبینی محتوای واردشده توسط n8n؛ پیش از انتشار باید تایید شود';
COMMENT ON COLUMN pending_prompts.status IS 'pending_review (پیش‌فرض) | approved | rejected';

-- جلوگیری از رکورد تکراری وقتی n8n دوباره اجرا می‌شود یا کانال را عقب‌تر
-- می‌خواند. توجه: در Postgres چند ردیف با NULL ناقض UNIQUE نیستند، پس این
-- محافظت فقط برای رکوردهایی کار می‌کند که هر دو ستون را دارند.
CREATE UNIQUE INDEX IF NOT EXISTS pending_prompts_source_unique
    ON pending_prompts (source_channel, source_message_id);

-- ---------------------------------------------------------------------------
-- گزارش فعالیت پنل مدیریت (migration 002)
-- ---------------------------------------------------------------------------
-- کارت «فعالیت‌های اخیر» داشبورد بدون این جدول یا باید داده‌ی جعلی نشان دهد یا
-- حذف شود. راه سوم همین است: هر نوشتنِ پنل یک ردیف اینجا می‌گذارد.
--
-- entity_id عمداً کلید خارجی نیست: مهم‌ترین رویدادِ ثبت‌شده «حذف» است و FK با
-- CASCADE همان ردیفِ گزارش را هم پاک می‌کرد. این جدول یک لاگ است، نه بخشی از
-- مدلِ داده.
CREATE TABLE IF NOT EXISTS admin_activity (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action      TEXT NOT NULL CHECK (action IN ('create', 'update', 'delete')),
    entity_type TEXT NOT NULL CHECK (entity_type IN ('image', 'category', 'prompt')),
    entity_id   BIGINT,
    -- خلاصه‌ی خواندنی در زمان رخداد (عنوان تصویر، نام دسته، ...). بعد از حذف
    -- رکورد، تنها ردِ باقی‌مانده است.
    summary     TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE admin_activity IS 'لاگ نوشتن‌های پنل مدیریت؛ منبع کارت «فعالیت‌های اخیر» داشبورد';
COMMENT ON COLUMN admin_activity.summary IS 'خلاصه‌ی خواندنی در زمان رخداد؛ بعد از حذف رکورد، تنها ردِ باقی‌مانده است';

-- ---------------------------------------------------------------------------
-- ایندکس‌ها — بر اساس کوئری‌هایی که گالری واقعاً می‌زند
-- ---------------------------------------------------------------------------

-- فیلتر تب دسته‌بندی: «عکس‌های این دسته». کلید اصلی جدول واسط با
-- (image_id, category_id) شروع می‌شود و برای جست‌وجو بر اساس category_id
-- کارآمد نیست؛ این ایندکس جدا دقیقاً برای همان مسیر معکوس است.
CREATE INDEX IF NOT EXISTS image_categories_category_id_idx
    ON image_categories (category_id);

-- ترتیب پیش‌فرض گالری: جدیدترین اول (و صفحه‌بندی/اسکرول بی‌نهایت روی همین)
CREATE INDEX IF NOT EXISTS images_created_at_idx ON images (created_at DESC);

-- مرتب‌سازی «محبوب‌ترین»
CREATE INDEX IF NOT EXISTS images_likes_count_idx ON images (likes_count DESC);

-- توجه: برای prompts.image_id ایندکس دستی نمی‌سازیم. قید UNIQUE روی آن ستون
-- خودش یک ایندکس btree می‌سازد، و ایندکس دوم فقط هزینه نوشتن و فضا اضافه
-- می‌کرد بدون هیچ سود خواندنی.

-- صفحه بازبینی ادمین: «کدام‌ها منتظر تاییدند؟»
CREATE INDEX IF NOT EXISTS pending_prompts_status_idx ON pending_prompts (status, created_at DESC);

-- داشبورد پنل: «آخرین N رویداد» — تنها کوئری این جدول همین است.
CREATE INDEX IF NOT EXISTS admin_activity_created_at_idx ON admin_activity (created_at DESC);

COMMIT;
